//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 06:23:17 PM GMT 
//


package org.sdmx.resources.sdmxml.schemas.v2_0.structure;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.sdmx.resources.sdmxml.schemas.v2_0.structure package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ContactTypeURI_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/structure", "URI");
    private final static QName _ContactTypeFax_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/structure", "Fax");
    private final static QName _ContactTypeTelephone_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/structure", "Telephone");
    private final static QName _ContactTypeEmail_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/structure", "Email");
    private final static QName _ContactTypeX400_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/structure", "X400");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.sdmx.resources.sdmxml.schemas.v2_0.structure
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CodeListType }
     * 
     */
    public CodeListType createCodeListType() {
        return new CodeListType();
    }

    /**
     * Create an instance of {@link CodeType }
     * 
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link CategoryMapType }
     * 
     */
    public CategoryMapType createCategoryMapType() {
        return new CategoryMapType();
    }

    /**
     * Create an instance of {@link HierarchicalCodelistsType }
     * 
     */
    public HierarchicalCodelistsType createHierarchicalCodelistsType() {
        return new HierarchicalCodelistsType();
    }

    /**
     * Create an instance of {@link StructureSetType }
     * 
     */
    public StructureSetType createStructureSetType() {
        return new StructureSetType();
    }

    /**
     * Create an instance of {@link FullTargetIdentifierType }
     * 
     */
    public FullTargetIdentifierType createFullTargetIdentifierType() {
        return new FullTargetIdentifierType();
    }

    /**
     * Create an instance of {@link HierarchicalCodelistType }
     * 
     */
    public HierarchicalCodelistType createHierarchicalCodelistType() {
        return new HierarchicalCodelistType();
    }

    /**
     * Create an instance of {@link CategorySchemeRefType }
     * 
     */
    public CategorySchemeRefType createCategorySchemeRefType() {
        return new CategorySchemeRefType();
    }

    /**
     * Create an instance of {@link ConceptSchemeType }
     * 
     */
    public ConceptSchemeType createConceptSchemeType() {
        return new ConceptSchemeType();
    }

    /**
     * Create an instance of {@link MetadataflowsType }
     * 
     */
    public MetadataflowsType createMetadataflowsType() {
        return new MetadataflowsType();
    }

    /**
     * Create an instance of {@link DataflowType }
     * 
     */
    public DataflowType createDataflowType() {
        return new DataflowType();
    }

    /**
     * Create an instance of {@link LevelType }
     * 
     */
    public LevelType createLevelType() {
        return new LevelType();
    }

    /**
     * Create an instance of {@link OrganisationSchemesType }
     * 
     */
    public OrganisationSchemesType createOrganisationSchemesType() {
        return new OrganisationSchemesType();
    }

    /**
     * Create an instance of {@link DimensionType }
     * 
     */
    public DimensionType createDimensionType() {
        return new DimensionType();
    }

    /**
     * Create an instance of {@link OrganisationMapType }
     * 
     */
    public OrganisationMapType createOrganisationMapType() {
        return new OrganisationMapType();
    }

    /**
     * Create an instance of {@link MetadataAttributeType }
     * 
     */
    public MetadataAttributeType createMetadataAttributeType() {
        return new MetadataAttributeType();
    }

    /**
     * Create an instance of {@link IdentifierComponentType }
     * 
     */
    public IdentifierComponentType createIdentifierComponentType() {
        return new IdentifierComponentType();
    }

    /**
     * Create an instance of {@link CategoryRefType }
     * 
     */
    public CategoryRefType createCategoryRefType() {
        return new CategoryRefType();
    }

    /**
     * Create an instance of {@link DataflowsType }
     * 
     */
    public DataflowsType createDataflowsType() {
        return new DataflowsType();
    }

    /**
     * Create an instance of {@link MetadataStructureDefinitionsType }
     * 
     */
    public MetadataStructureDefinitionsType createMetadataStructureDefinitionsType() {
        return new MetadataStructureDefinitionsType();
    }

    /**
     * Create an instance of {@link CodeRefType }
     * 
     */
    public CodeRefType createCodeRefType() {
        return new CodeRefType();
    }

    /**
     * Create an instance of {@link DataflowRefType }
     * 
     */
    public DataflowRefType createDataflowRefType() {
        return new DataflowRefType();
    }

    /**
     * Create an instance of {@link OrganisationSchemeType }
     * 
     */
    public OrganisationSchemeType createOrganisationSchemeType() {
        return new OrganisationSchemeType();
    }

    /**
     * Create an instance of {@link OrganisationSchemeMapType }
     * 
     */
    public OrganisationSchemeMapType createOrganisationSchemeMapType() {
        return new OrganisationSchemeMapType();
    }

    /**
     * Create an instance of {@link ConceptSchemeMapType }
     * 
     */
    public ConceptSchemeMapType createConceptSchemeMapType() {
        return new ConceptSchemeMapType();
    }

    /**
     * Create an instance of {@link RepresentationMapRefType }
     * 
     */
    public RepresentationMapRefType createRepresentationMapRefType() {
        return new RepresentationMapRefType();
    }

    /**
     * Create an instance of {@link StructureSetsType }
     * 
     */
    public StructureSetsType createStructureSetsType() {
        return new StructureSetsType();
    }

    /**
     * Create an instance of {@link RelatedStructuresType }
     * 
     */
    public RelatedStructuresType createRelatedStructuresType() {
        return new RelatedStructuresType();
    }

    /**
     * Create an instance of {@link DataProvidersType }
     * 
     */
    public DataProvidersType createDataProvidersType() {
        return new DataProvidersType();
    }

    /**
     * Create an instance of {@link MetadataflowType }
     * 
     */
    public MetadataflowType createMetadataflowType() {
        return new MetadataflowType();
    }

    /**
     * Create an instance of {@link TextFormatType }
     * 
     */
    public TextFormatType createTextFormatType() {
        return new TextFormatType();
    }

    /**
     * Create an instance of {@link ComponentsType }
     * 
     */
    public ComponentsType createComponentsType() {
        return new ComponentsType();
    }

    /**
     * Create an instance of {@link GroupType }
     * 
     */
    public GroupType createGroupType() {
        return new GroupType();
    }

    /**
     * Create an instance of {@link ConceptSchemeRefType }
     * 
     */
    public ConceptSchemeRefType createConceptSchemeRefType() {
        return new ConceptSchemeRefType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link ProcessesType }
     * 
     */
    public ProcessesType createProcessesType() {
        return new ProcessesType();
    }

    /**
     * Create an instance of {@link RepresentationSchemeType }
     * 
     */
    public RepresentationSchemeType createRepresentationSchemeType() {
        return new RepresentationSchemeType();
    }

    /**
     * Create an instance of {@link ConceptsType }
     * 
     */
    public ConceptsType createConceptsType() {
        return new ConceptsType();
    }

    /**
     * Create an instance of {@link HierarchicalCodelistRefType }
     * 
     */
    public HierarchicalCodelistRefType createHierarchicalCodelistRefType() {
        return new HierarchicalCodelistRefType();
    }

    /**
     * Create an instance of {@link KeyFamilyRefType }
     * 
     */
    public KeyFamilyRefType createKeyFamilyRefType() {
        return new KeyFamilyRefType();
    }

    /**
     * Create an instance of {@link ReportingTaxonomyType }
     * 
     */
    public ReportingTaxonomyType createReportingTaxonomyType() {
        return new ReportingTaxonomyType();
    }

    /**
     * Create an instance of {@link ConceptType }
     * 
     */
    public ConceptType createConceptType() {
        return new ConceptType();
    }

    /**
     * Create an instance of {@link ProcessStepType }
     * 
     */
    public ProcessStepType createProcessStepType() {
        return new ProcessStepType();
    }

    /**
     * Create an instance of {@link CategorySchemesType }
     * 
     */
    public CategorySchemesType createCategorySchemesType() {
        return new CategorySchemesType();
    }

    /**
     * Create an instance of {@link ReportStructureType }
     * 
     */
    public ReportStructureType createReportStructureType() {
        return new ReportStructureType();
    }

    /**
     * Create an instance of {@link ContactType }
     * 
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link CodelistRefType }
     * 
     */
    public CodelistRefType createCodelistRefType() {
        return new CodelistRefType();
    }

    /**
     * Create an instance of {@link DataConsumersType }
     * 
     */
    public DataConsumersType createDataConsumersType() {
        return new DataConsumersType();
    }

    /**
     * Create an instance of {@link ProcessType }
     * 
     */
    public ProcessType createProcessType() {
        return new ProcessType();
    }

    /**
     * Create an instance of {@link ConceptMapType }
     * 
     */
    public ConceptMapType createConceptMapType() {
        return new ConceptMapType();
    }

    /**
     * Create an instance of {@link KeyFamiliesType }
     * 
     */
    public KeyFamiliesType createKeyFamiliesType() {
        return new KeyFamiliesType();
    }

    /**
     * Create an instance of {@link DataProviderRefType }
     * 
     */
    public DataProviderRefType createDataProviderRefType() {
        return new DataProviderRefType();
    }

    /**
     * Create an instance of {@link AttachmentConstraintRefType }
     * 
     */
    public AttachmentConstraintRefType createAttachmentConstraintRefType() {
        return new AttachmentConstraintRefType();
    }

    /**
     * Create an instance of {@link CodelistMapType }
     * 
     */
    public CodelistMapType createCodelistMapType() {
        return new CodelistMapType();
    }

    /**
     * Create an instance of {@link MetadataStructureRefType }
     * 
     */
    public MetadataStructureRefType createMetadataStructureRefType() {
        return new MetadataStructureRefType();
    }

    /**
     * Create an instance of {@link ProvisionAgreementRefType }
     * 
     */
    public ProvisionAgreementRefType createProvisionAgreementRefType() {
        return new ProvisionAgreementRefType();
    }

    /**
     * Create an instance of {@link CrossSectionalMeasureType }
     * 
     */
    public CrossSectionalMeasureType createCrossSectionalMeasureType() {
        return new CrossSectionalMeasureType();
    }

    /**
     * Create an instance of {@link OrganisationType }
     * 
     */
    public OrganisationType createOrganisationType() {
        return new OrganisationType();
    }

    /**
     * Create an instance of {@link CodeMapType }
     * 
     */
    public CodeMapType createCodeMapType() {
        return new CodeMapType();
    }

    /**
     * Create an instance of {@link CategorySchemeType }
     * 
     */
    public CategorySchemeType createCategorySchemeType() {
        return new CategorySchemeType();
    }

    /**
     * Create an instance of {@link PrimaryMeasureType }
     * 
     */
    public PrimaryMeasureType createPrimaryMeasureType() {
        return new PrimaryMeasureType();
    }

    /**
     * Create an instance of {@link CategoryIDType }
     * 
     */
    public CategoryIDType createCategoryIDType() {
        return new CategoryIDType();
    }

    /**
     * Create an instance of {@link ComponentMapType }
     * 
     */
    public ComponentMapType createComponentMapType() {
        return new ComponentMapType();
    }

    /**
     * Create an instance of {@link StructureMapType }
     * 
     */
    public StructureMapType createStructureMapType() {
        return new StructureMapType();
    }

    /**
     * Create an instance of {@link PartialTargetIdentifierType }
     * 
     */
    public PartialTargetIdentifierType createPartialTargetIdentifierType() {
        return new PartialTargetIdentifierType();
    }

    /**
     * Create an instance of {@link KeyFamilyType }
     * 
     */
    public KeyFamilyType createKeyFamilyType() {
        return new KeyFamilyType();
    }

    /**
     * Create an instance of {@link TransitionType }
     * 
     */
    public TransitionType createTransitionType() {
        return new TransitionType();
    }

    /**
     * Create an instance of {@link OrganisationSchemeRefType }
     * 
     */
    public OrganisationSchemeRefType createOrganisationSchemeRefType() {
        return new OrganisationSchemeRefType();
    }

    /**
     * Create an instance of {@link MetadataflowRefType }
     * 
     */
    public MetadataflowRefType createMetadataflowRefType() {
        return new MetadataflowRefType();
    }

    /**
     * Create an instance of {@link CategorySchemeMapType }
     * 
     */
    public CategorySchemeMapType createCategorySchemeMapType() {
        return new CategorySchemeMapType();
    }

    /**
     * Create an instance of {@link CategoryType }
     * 
     */
    public CategoryType createCategoryType() {
        return new CategoryType();
    }

    /**
     * Create an instance of {@link MetadataStructureDefinitionType }
     * 
     */
    public MetadataStructureDefinitionType createMetadataStructureDefinitionType() {
        return new MetadataStructureDefinitionType();
    }

    /**
     * Create an instance of {@link TargetIdentifiersType }
     * 
     */
    public TargetIdentifiersType createTargetIdentifiersType() {
        return new TargetIdentifiersType();
    }

    /**
     * Create an instance of {@link TimeDimensionType }
     * 
     */
    public TimeDimensionType createTimeDimensionType() {
        return new TimeDimensionType();
    }

    /**
     * Create an instance of {@link HierarchyType }
     * 
     */
    public HierarchyType createHierarchyType() {
        return new HierarchyType();
    }

    /**
     * Create an instance of {@link AgenciesType }
     * 
     */
    public AgenciesType createAgenciesType() {
        return new AgenciesType();
    }

    /**
     * Create an instance of {@link ReportingTaxonomiesType }
     * 
     */
    public ReportingTaxonomiesType createReportingTaxonomiesType() {
        return new ReportingTaxonomiesType();
    }

    /**
     * Create an instance of {@link CodeListsType }
     * 
     */
    public CodeListsType createCodeListsType() {
        return new CodeListsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/structure", name = "URI", scope = ContactType.class)
    public JAXBElement<String> createContactTypeURI(String value) {
        return new JAXBElement<String>(_ContactTypeURI_QNAME, String.class, ContactType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/structure", name = "Fax", scope = ContactType.class)
    public JAXBElement<String> createContactTypeFax(String value) {
        return new JAXBElement<String>(_ContactTypeFax_QNAME, String.class, ContactType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/structure", name = "Telephone", scope = ContactType.class)
    public JAXBElement<String> createContactTypeTelephone(String value) {
        return new JAXBElement<String>(_ContactTypeTelephone_QNAME, String.class, ContactType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/structure", name = "Email", scope = ContactType.class)
    public JAXBElement<String> createContactTypeEmail(String value) {
        return new JAXBElement<String>(_ContactTypeEmail_QNAME, String.class, ContactType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/structure", name = "X400", scope = ContactType.class)
    public JAXBElement<String> createContactTypeX400(String value) {
        return new JAXBElement<String>(_ContactTypeX400_QNAME, String.class, ContactType.class, value);
    }

}
