//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 06:23:17 PM GMT 
//


package org.sdmx.resources.sdmxml.schemas.v2_0.registry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * QueryProvisioningRequest is used to query the repository for provisioning metadata. The response is a QueryProvisioningResponse document, carrying either the result set of the query or relevant error messages. Note that whatever information is presented here, regarding provision agreements, data flow, metadataflow, or data providers, is taken to be the search criteria - the query is for all provision agreements which match the supplied criteria. If any of provision agreement, metadataflow, dataflow, or data provider are omitted, the search will apply to all values for those objects in the repository.
 * 
 * <p>Java class for QueryProvisioningRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryProvisioningRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProvisionAgreementRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}ProvisionAgreementRefType" minOccurs="0"/>
 *         &lt;element name="DataflowRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}DataflowRefType" minOccurs="0"/>
 *         &lt;element name="MetadataflowRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}MetadataflowRefType" minOccurs="0"/>
 *         &lt;element name="DataProviderRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}DataProviderRefType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryProvisioningRequestType", propOrder = {
    "provisionAgreementRef",
    "dataflowRef",
    "metadataflowRef",
    "dataProviderRef"
})
public class QueryProvisioningRequestType {

    @XmlElement(name = "ProvisionAgreementRef")
    protected ProvisionAgreementRefType provisionAgreementRef;
    @XmlElement(name = "DataflowRef")
    protected DataflowRefType dataflowRef;
    @XmlElement(name = "MetadataflowRef")
    protected MetadataflowRefType metadataflowRef;
    @XmlElement(name = "DataProviderRef")
    protected DataProviderRefType dataProviderRef;

    /**
     * Gets the value of the provisionAgreementRef property.
     * 
     * @return
     *     possible object is
     *     {@link ProvisionAgreementRefType }
     *     
     */
    public ProvisionAgreementRefType getProvisionAgreementRef() {
        return provisionAgreementRef;
    }

    /**
     * Sets the value of the provisionAgreementRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProvisionAgreementRefType }
     *     
     */
    public void setProvisionAgreementRef(ProvisionAgreementRefType value) {
        this.provisionAgreementRef = value;
    }

    /**
     * Gets the value of the dataflowRef property.
     * 
     * @return
     *     possible object is
     *     {@link DataflowRefType }
     *     
     */
    public DataflowRefType getDataflowRef() {
        return dataflowRef;
    }

    /**
     * Sets the value of the dataflowRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataflowRefType }
     *     
     */
    public void setDataflowRef(DataflowRefType value) {
        this.dataflowRef = value;
    }

    /**
     * Gets the value of the metadataflowRef property.
     * 
     * @return
     *     possible object is
     *     {@link MetadataflowRefType }
     *     
     */
    public MetadataflowRefType getMetadataflowRef() {
        return metadataflowRef;
    }

    /**
     * Sets the value of the metadataflowRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetadataflowRefType }
     *     
     */
    public void setMetadataflowRef(MetadataflowRefType value) {
        this.metadataflowRef = value;
    }

    /**
     * Gets the value of the dataProviderRef property.
     * 
     * @return
     *     possible object is
     *     {@link DataProviderRefType }
     *     
     */
    public DataProviderRefType getDataProviderRef() {
        return dataProviderRef;
    }

    /**
     * Sets the value of the dataProviderRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataProviderRefType }
     *     
     */
    public void setDataProviderRef(DataProviderRefType value) {
        this.dataProviderRef = value;
    }

}
