//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 06:23:17 PM GMT 
//


package uk.ac.cardiff.raptor.sdmx.compact;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CL_COLLECTION.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CL_COLLECTION">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="B"/>
 *     &lt;enumeration value="E"/>
 *     &lt;enumeration value="H"/>
 *     &lt;enumeration value="L"/>
 *     &lt;enumeration value="M"/>
 *     &lt;enumeration value="S"/>
 *     &lt;enumeration value="U"/>
 *     &lt;enumeration value="V"/>
 *     &lt;enumeration value="Y"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CL_COLLECTION")
@XmlEnum
public enum CLCOLLECTION {


    /**
     * Average of observations through period
     * 
     */
    A,

    /**
     * Beginning of period
     * 
     */
    B,

    /**
     * End of period
     * 
     */
    E,

    /**
     * Highest in period
     * 
     */
    H,

    /**
     * Lowest in period
     * 
     */
    L,

    /**
     * Middle of period
     * 
     */
    M,

    /**
     * Summed through period
     * 
     */
    S,

    /**
     * Unknown
     * 
     */
    U,

    /**
     * Other
     * 
     */
    V,

    /**
     * Annualized
     * 
     */
    Y;

    public String value() {
        return name();
    }

    public static CLCOLLECTION fromValue(String v) {
        return valueOf(v);
    }

}
