//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 06:23:17 PM GMT 
//


package org.sdmx.resources.sdmxml.schemas.v2_0.registry;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * QueryStructureRequest is used to query the registry for any maintainable object within the repository. The response is a Structure message. In the reference elements to the queryable registry objects, a valid registry URN or a complete set of other child elements may be used to identify the objects desired in the result set. Any part of an element-based (that is, non-URN) identification of an object which is not provided will be understood as a wild-card value, referring to "all" possible values. The resolveReferences attribute is set to true if all dependent objects should also be returned as part of the result set. (For example, if you query for a key family and want to also have all codelists, concepts, and agencies, returned as well, resolveReferences should be set to true.)
 * 
 * <p>Java class for QueryStructureRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryStructureRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="AgencyRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}AgencyRefType"/>
 *         &lt;element name="DataProviderRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}DataProviderRefType"/>
 *         &lt;element name="DataflowRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}DataflowRefType"/>
 *         &lt;element name="MetadataflowRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}MetadataflowRefType"/>
 *         &lt;element name="CodelistRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}CodelistRefType"/>
 *         &lt;element name="CategorySchemeRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}CategorySchemeRefType"/>
 *         &lt;element name="ConceptSchemeRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}ConceptSchemeRefType"/>
 *         &lt;element name="OrganisationSchemeRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}OrganisationSchemeRefType"/>
 *         &lt;element name="KeyFamilyRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}KeyFamilyRefType"/>
 *         &lt;element name="MetadataStructureRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}MetadataStructureRefType"/>
 *         &lt;element name="HierarchicalCodelistRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}HierarchicalCodelistRefType"/>
 *         &lt;element name="StructureSetRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}StructureSetRefType"/>
 *         &lt;element name="ProcessRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}ProcessRefType"/>
 *         &lt;element name="ReportingTaxonomyRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}ReportingTaxonomyRefType"/>
 *       &lt;/choice>
 *       &lt;attribute name="resolveReferences" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryStructureRequestType", propOrder = {
    "agencyRefOrDataProviderRefOrDataflowRef"
})
public class QueryStructureRequestType {

    @XmlElements({
        @XmlElement(name = "KeyFamilyRef", type = KeyFamilyRefType.class),
        @XmlElement(name = "ConceptSchemeRef", type = ConceptSchemeRefType.class),
        @XmlElement(name = "OrganisationSchemeRef", type = OrganisationSchemeRefType.class),
        @XmlElement(name = "ReportingTaxonomyRef", type = ReportingTaxonomyRefType.class),
        @XmlElement(name = "ProcessRef", type = ProcessRefType.class),
        @XmlElement(name = "DataflowRef", type = DataflowRefType.class),
        @XmlElement(name = "StructureSetRef", type = StructureSetRefType.class),
        @XmlElement(name = "CodelistRef", type = CodelistRefType.class),
        @XmlElement(name = "CategorySchemeRef", type = CategorySchemeRefType.class),
        @XmlElement(name = "DataProviderRef", type = DataProviderRefType.class),
        @XmlElement(name = "MetadataStructureRef", type = MetadataStructureRefType.class),
        @XmlElement(name = "AgencyRef", type = AgencyRefType.class),
        @XmlElement(name = "HierarchicalCodelistRef", type = HierarchicalCodelistRefType.class),
        @XmlElement(name = "MetadataflowRef", type = MetadataflowRefType.class)
    })
    protected List<Object> agencyRefOrDataProviderRefOrDataflowRef;
    @XmlAttribute(required = true)
    protected boolean resolveReferences;

    /**
     * Gets the value of the agencyRefOrDataProviderRefOrDataflowRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agencyRefOrDataProviderRefOrDataflowRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgencyRefOrDataProviderRefOrDataflowRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeyFamilyRefType }
     * {@link ConceptSchemeRefType }
     * {@link OrganisationSchemeRefType }
     * {@link ReportingTaxonomyRefType }
     * {@link ProcessRefType }
     * {@link DataflowRefType }
     * {@link StructureSetRefType }
     * {@link CodelistRefType }
     * {@link CategorySchemeRefType }
     * {@link DataProviderRefType }
     * {@link MetadataStructureRefType }
     * {@link AgencyRefType }
     * {@link HierarchicalCodelistRefType }
     * {@link MetadataflowRefType }
     * 
     * 
     */
    public List<Object> getAgencyRefOrDataProviderRefOrDataflowRef() {
        if (agencyRefOrDataProviderRefOrDataflowRef == null) {
            agencyRefOrDataProviderRefOrDataflowRef = new ArrayList<Object>();
        }
        return this.agencyRefOrDataProviderRefOrDataflowRef;
    }

    /**
     * Gets the value of the resolveReferences property.
     * 
     */
    public boolean isResolveReferences() {
        return resolveReferences;
    }

    /**
     * Sets the value of the resolveReferences property.
     * 
     */
    public void setResolveReferences(boolean value) {
        this.resolveReferences = value;
    }

}
