//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 06:23:17 PM GMT 
//


package org.sdmx.resources.sdmxml.schemas.v2_0.structure;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Representation schemes indicated which values are valid for identifying objects within each class. For any given representation scheme, two IDs must be provided: the RepresentationScheme must have an ID as assigned to it by it representationSchemeAgency, whose ID must also be provided. The type of the representation scheme is expressed in the representationSchemeType attribute.
 * 
 * <p>Java class for RepresentationSchemeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RepresentationSchemeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="representationScheme" use="required" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType" />
 *       &lt;attribute name="representationSchemeAgency" use="required" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType" />
 *       &lt;attribute name="representationSchemeType" use="required" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/structure}RepresentationSchemeTypeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RepresentationSchemeType")
public class RepresentationSchemeType {

    @XmlAttribute(required = true)
    protected String representationScheme;
    @XmlAttribute(required = true)
    protected String representationSchemeAgency;
    @XmlAttribute(required = true)
    protected RepresentationSchemeTypeType representationSchemeType;

    /**
     * Gets the value of the representationScheme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepresentationScheme() {
        return representationScheme;
    }

    /**
     * Sets the value of the representationScheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepresentationScheme(String value) {
        this.representationScheme = value;
    }

    /**
     * Gets the value of the representationSchemeAgency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepresentationSchemeAgency() {
        return representationSchemeAgency;
    }

    /**
     * Sets the value of the representationSchemeAgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepresentationSchemeAgency(String value) {
        this.representationSchemeAgency = value;
    }

    /**
     * Gets the value of the representationSchemeType property.
     * 
     * @return
     *     possible object is
     *     {@link RepresentationSchemeTypeType }
     *     
     */
    public RepresentationSchemeTypeType getRepresentationSchemeType() {
        return representationSchemeType;
    }

    /**
     * Sets the value of the representationSchemeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepresentationSchemeTypeType }
     *     
     */
    public void setRepresentationSchemeType(RepresentationSchemeTypeType value) {
        this.representationSchemeType = value;
    }

}
