//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 06:23:17 PM GMT 
//


package org.sdmx.resources.sdmxml.schemas.v2_0.structure;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * CodeMap describes the equivalence of the codes in the referenced codelist or hierarchical codelist indicated in the CodelistRef element of the containing CodelistMap to those in the referenced TargetCodelist in the containing CodelistMap. The CodeAlias attribute is used to assign an alias code to the equivalence for querying the structure set.
 * 
 * <p>Java class for CodeMapType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CodeMapType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MapCodeRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType"/>
 *         &lt;element name="MapTargetCodeRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CodeAlias" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodeMapType", propOrder = {
    "mapCodeRef",
    "mapTargetCodeRef"
})
public class CodeMapType {

    @XmlElement(name = "MapCodeRef", required = true)
    protected String mapCodeRef;
    @XmlElement(name = "MapTargetCodeRef", required = true)
    protected String mapTargetCodeRef;
    @XmlAttribute(name = "CodeAlias")
    protected String codeAlias;

    /**
     * Gets the value of the mapCodeRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMapCodeRef() {
        return mapCodeRef;
    }

    /**
     * Sets the value of the mapCodeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMapCodeRef(String value) {
        this.mapCodeRef = value;
    }

    /**
     * Gets the value of the mapTargetCodeRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMapTargetCodeRef() {
        return mapTargetCodeRef;
    }

    /**
     * Sets the value of the mapTargetCodeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMapTargetCodeRef(String value) {
        this.mapTargetCodeRef = value;
    }

    /**
     * Gets the value of the codeAlias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeAlias() {
        return codeAlias;
    }

    /**
     * Sets the value of the codeAlias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeAlias(String value) {
        this.codeAlias = value;
    }

}
