//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 06:23:17 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:uk:ac:cardiff:raptor:sdmx:compact", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.ac.cardiff.raptor.sdmx.compact;
