//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 06:23:17 PM GMT 
//


package org.sdmx.resources.sdmxml.schemas.v2_0.registry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Datasource specifies the properties of a data or metadata source. A SimpleDatasource requires only the URL of the data. A QueryableDatasource must be able to accept an SDMX-ML Query Message, and respond appropriately. Either or both may be specified.
 * 
 * <p>Java class for DatasourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatasourceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SimpleDatasource" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="QueryableDatasource" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}QueryableDatasourceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatasourceType", propOrder = {
    "simpleDatasource",
    "queryableDatasource"
})
public class DatasourceType {

    @XmlElement(name = "SimpleDatasource")
    @XmlSchemaType(name = "anyURI")
    protected String simpleDatasource;
    @XmlElement(name = "QueryableDatasource")
    protected QueryableDatasourceType queryableDatasource;

    /**
     * Gets the value of the simpleDatasource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimpleDatasource() {
        return simpleDatasource;
    }

    /**
     * Sets the value of the simpleDatasource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimpleDatasource(String value) {
        this.simpleDatasource = value;
    }

    /**
     * Gets the value of the queryableDatasource property.
     * 
     * @return
     *     possible object is
     *     {@link QueryableDatasourceType }
     *     
     */
    public QueryableDatasourceType getQueryableDatasource() {
        return queryableDatasource;
    }

    /**
     * Sets the value of the queryableDatasource property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryableDatasourceType }
     *     
     */
    public void setQueryableDatasource(QueryableDatasourceType value) {
        this.queryableDatasource = value;
    }

}
