//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 06:23:17 PM GMT 
//


package org.sdmx.resources.sdmxml.schemas.v2_0.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.sdmx.resources.sdmxml.schemas.v2_0.registry.NotifyRegistryEventType;
import org.sdmx.resources.sdmxml.schemas.v2_0.registry.QueryProvisioningRequestType;
import org.sdmx.resources.sdmxml.schemas.v2_0.registry.QueryProvisioningResponseType;
import org.sdmx.resources.sdmxml.schemas.v2_0.registry.QueryRegistrationRequestType;
import org.sdmx.resources.sdmxml.schemas.v2_0.registry.QueryRegistrationResponseType;
import org.sdmx.resources.sdmxml.schemas.v2_0.registry.QueryStructureRequestType;
import org.sdmx.resources.sdmxml.schemas.v2_0.registry.QueryStructureResponseType;
import org.sdmx.resources.sdmxml.schemas.v2_0.registry.SubmitProvisioningRequestType;
import org.sdmx.resources.sdmxml.schemas.v2_0.registry.SubmitProvisioningResponseType;
import org.sdmx.resources.sdmxml.schemas.v2_0.registry.SubmitRegistrationRequestType;
import org.sdmx.resources.sdmxml.schemas.v2_0.registry.SubmitRegistrationResponseType;
import org.sdmx.resources.sdmxml.schemas.v2_0.registry.SubmitStructureRequestType;
import org.sdmx.resources.sdmxml.schemas.v2_0.registry.SubmitStructureResponseType;
import org.sdmx.resources.sdmxml.schemas.v2_0.registry.SubmitSubscriptionRequestType;
import org.sdmx.resources.sdmxml.schemas.v2_0.registry.SubmitSubscriptionResponseType;


/**
 * This is a type which describes a structure for holding all of the various dedicated registry interface message types.
 * 
 * <p>Java class for RegistryInterfaceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistryInterfaceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message}MessageType">
 *       &lt;choice>
 *         &lt;element name="SubmitSubscriptionRequest" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}SubmitSubscriptionRequestType"/>
 *         &lt;element name="SubmitSubscriptionResponse" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}SubmitSubscriptionResponseType"/>
 *         &lt;element name="NotifyRegistryEvent" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}NotifyRegistryEventType"/>
 *         &lt;element name="SubmitRegistrationRequest" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}SubmitRegistrationRequestType"/>
 *         &lt;element name="SubmitRegistrationResponse" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}SubmitRegistrationResponseType"/>
 *         &lt;element name="QueryRegistrationRequest" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}QueryRegistrationRequestType"/>
 *         &lt;element name="QueryRegistrationResponse" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}QueryRegistrationResponseType"/>
 *         &lt;element name="SubmitStructureRequest" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}SubmitStructureRequestType"/>
 *         &lt;element name="SubmitStructureResponse" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}SubmitStructureResponseType"/>
 *         &lt;element name="QueryStructureRequest" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}QueryStructureRequestType"/>
 *         &lt;element name="QueryStructureResponse" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}QueryStructureResponseType"/>
 *         &lt;element name="SubmitProvisioningRequest" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}SubmitProvisioningRequestType"/>
 *         &lt;element name="SubmitProvisioningResponse" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}SubmitProvisioningResponseType"/>
 *         &lt;element name="QueryProvisioningRequest" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}QueryProvisioningRequestType"/>
 *         &lt;element name="QueryProvisioningResponse" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}QueryProvisioningResponseType"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistryInterfaceType", propOrder = {
    "submitSubscriptionRequest",
    "submitSubscriptionResponse",
    "notifyRegistryEvent",
    "submitRegistrationRequest",
    "submitRegistrationResponse",
    "queryRegistrationRequest",
    "queryRegistrationResponse",
    "submitStructureRequest",
    "submitStructureResponse",
    "queryStructureRequest",
    "queryStructureResponse",
    "submitProvisioningRequest",
    "submitProvisioningResponse",
    "queryProvisioningRequest",
    "queryProvisioningResponse"
})
public class RegistryInterfaceType
    extends MessageType
{

    @XmlElement(name = "SubmitSubscriptionRequest")
    protected SubmitSubscriptionRequestType submitSubscriptionRequest;
    @XmlElement(name = "SubmitSubscriptionResponse")
    protected SubmitSubscriptionResponseType submitSubscriptionResponse;
    @XmlElement(name = "NotifyRegistryEvent")
    protected NotifyRegistryEventType notifyRegistryEvent;
    @XmlElement(name = "SubmitRegistrationRequest")
    protected SubmitRegistrationRequestType submitRegistrationRequest;
    @XmlElement(name = "SubmitRegistrationResponse")
    protected SubmitRegistrationResponseType submitRegistrationResponse;
    @XmlElement(name = "QueryRegistrationRequest")
    protected QueryRegistrationRequestType queryRegistrationRequest;
    @XmlElement(name = "QueryRegistrationResponse")
    protected QueryRegistrationResponseType queryRegistrationResponse;
    @XmlElement(name = "SubmitStructureRequest")
    protected SubmitStructureRequestType submitStructureRequest;
    @XmlElement(name = "SubmitStructureResponse")
    protected SubmitStructureResponseType submitStructureResponse;
    @XmlElement(name = "QueryStructureRequest")
    protected QueryStructureRequestType queryStructureRequest;
    @XmlElement(name = "QueryStructureResponse")
    protected QueryStructureResponseType queryStructureResponse;
    @XmlElement(name = "SubmitProvisioningRequest")
    protected SubmitProvisioningRequestType submitProvisioningRequest;
    @XmlElement(name = "SubmitProvisioningResponse")
    protected SubmitProvisioningResponseType submitProvisioningResponse;
    @XmlElement(name = "QueryProvisioningRequest")
    protected QueryProvisioningRequestType queryProvisioningRequest;
    @XmlElement(name = "QueryProvisioningResponse")
    protected QueryProvisioningResponseType queryProvisioningResponse;

    /**
     * Gets the value of the submitSubscriptionRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitSubscriptionRequestType }
     *     
     */
    public SubmitSubscriptionRequestType getSubmitSubscriptionRequest() {
        return submitSubscriptionRequest;
    }

    /**
     * Sets the value of the submitSubscriptionRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitSubscriptionRequestType }
     *     
     */
    public void setSubmitSubscriptionRequest(SubmitSubscriptionRequestType value) {
        this.submitSubscriptionRequest = value;
    }

    /**
     * Gets the value of the submitSubscriptionResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitSubscriptionResponseType }
     *     
     */
    public SubmitSubscriptionResponseType getSubmitSubscriptionResponse() {
        return submitSubscriptionResponse;
    }

    /**
     * Sets the value of the submitSubscriptionResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitSubscriptionResponseType }
     *     
     */
    public void setSubmitSubscriptionResponse(SubmitSubscriptionResponseType value) {
        this.submitSubscriptionResponse = value;
    }

    /**
     * Gets the value of the notifyRegistryEvent property.
     * 
     * @return
     *     possible object is
     *     {@link NotifyRegistryEventType }
     *     
     */
    public NotifyRegistryEventType getNotifyRegistryEvent() {
        return notifyRegistryEvent;
    }

    /**
     * Sets the value of the notifyRegistryEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotifyRegistryEventType }
     *     
     */
    public void setNotifyRegistryEvent(NotifyRegistryEventType value) {
        this.notifyRegistryEvent = value;
    }

    /**
     * Gets the value of the submitRegistrationRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitRegistrationRequestType }
     *     
     */
    public SubmitRegistrationRequestType getSubmitRegistrationRequest() {
        return submitRegistrationRequest;
    }

    /**
     * Sets the value of the submitRegistrationRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitRegistrationRequestType }
     *     
     */
    public void setSubmitRegistrationRequest(SubmitRegistrationRequestType value) {
        this.submitRegistrationRequest = value;
    }

    /**
     * Gets the value of the submitRegistrationResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitRegistrationResponseType }
     *     
     */
    public SubmitRegistrationResponseType getSubmitRegistrationResponse() {
        return submitRegistrationResponse;
    }

    /**
     * Sets the value of the submitRegistrationResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitRegistrationResponseType }
     *     
     */
    public void setSubmitRegistrationResponse(SubmitRegistrationResponseType value) {
        this.submitRegistrationResponse = value;
    }

    /**
     * Gets the value of the queryRegistrationRequest property.
     * 
     * @return
     *     possible object is
     *     {@link QueryRegistrationRequestType }
     *     
     */
    public QueryRegistrationRequestType getQueryRegistrationRequest() {
        return queryRegistrationRequest;
    }

    /**
     * Sets the value of the queryRegistrationRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryRegistrationRequestType }
     *     
     */
    public void setQueryRegistrationRequest(QueryRegistrationRequestType value) {
        this.queryRegistrationRequest = value;
    }

    /**
     * Gets the value of the queryRegistrationResponse property.
     * 
     * @return
     *     possible object is
     *     {@link QueryRegistrationResponseType }
     *     
     */
    public QueryRegistrationResponseType getQueryRegistrationResponse() {
        return queryRegistrationResponse;
    }

    /**
     * Sets the value of the queryRegistrationResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryRegistrationResponseType }
     *     
     */
    public void setQueryRegistrationResponse(QueryRegistrationResponseType value) {
        this.queryRegistrationResponse = value;
    }

    /**
     * Gets the value of the submitStructureRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitStructureRequestType }
     *     
     */
    public SubmitStructureRequestType getSubmitStructureRequest() {
        return submitStructureRequest;
    }

    /**
     * Sets the value of the submitStructureRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitStructureRequestType }
     *     
     */
    public void setSubmitStructureRequest(SubmitStructureRequestType value) {
        this.submitStructureRequest = value;
    }

    /**
     * Gets the value of the submitStructureResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitStructureResponseType }
     *     
     */
    public SubmitStructureResponseType getSubmitStructureResponse() {
        return submitStructureResponse;
    }

    /**
     * Sets the value of the submitStructureResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitStructureResponseType }
     *     
     */
    public void setSubmitStructureResponse(SubmitStructureResponseType value) {
        this.submitStructureResponse = value;
    }

    /**
     * Gets the value of the queryStructureRequest property.
     * 
     * @return
     *     possible object is
     *     {@link QueryStructureRequestType }
     *     
     */
    public QueryStructureRequestType getQueryStructureRequest() {
        return queryStructureRequest;
    }

    /**
     * Sets the value of the queryStructureRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryStructureRequestType }
     *     
     */
    public void setQueryStructureRequest(QueryStructureRequestType value) {
        this.queryStructureRequest = value;
    }

    /**
     * Gets the value of the queryStructureResponse property.
     * 
     * @return
     *     possible object is
     *     {@link QueryStructureResponseType }
     *     
     */
    public QueryStructureResponseType getQueryStructureResponse() {
        return queryStructureResponse;
    }

    /**
     * Sets the value of the queryStructureResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryStructureResponseType }
     *     
     */
    public void setQueryStructureResponse(QueryStructureResponseType value) {
        this.queryStructureResponse = value;
    }

    /**
     * Gets the value of the submitProvisioningRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitProvisioningRequestType }
     *     
     */
    public SubmitProvisioningRequestType getSubmitProvisioningRequest() {
        return submitProvisioningRequest;
    }

    /**
     * Sets the value of the submitProvisioningRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitProvisioningRequestType }
     *     
     */
    public void setSubmitProvisioningRequest(SubmitProvisioningRequestType value) {
        this.submitProvisioningRequest = value;
    }

    /**
     * Gets the value of the submitProvisioningResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitProvisioningResponseType }
     *     
     */
    public SubmitProvisioningResponseType getSubmitProvisioningResponse() {
        return submitProvisioningResponse;
    }

    /**
     * Sets the value of the submitProvisioningResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitProvisioningResponseType }
     *     
     */
    public void setSubmitProvisioningResponse(SubmitProvisioningResponseType value) {
        this.submitProvisioningResponse = value;
    }

    /**
     * Gets the value of the queryProvisioningRequest property.
     * 
     * @return
     *     possible object is
     *     {@link QueryProvisioningRequestType }
     *     
     */
    public QueryProvisioningRequestType getQueryProvisioningRequest() {
        return queryProvisioningRequest;
    }

    /**
     * Sets the value of the queryProvisioningRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryProvisioningRequestType }
     *     
     */
    public void setQueryProvisioningRequest(QueryProvisioningRequestType value) {
        this.queryProvisioningRequest = value;
    }

    /**
     * Gets the value of the queryProvisioningResponse property.
     * 
     * @return
     *     possible object is
     *     {@link QueryProvisioningResponseType }
     *     
     */
    public QueryProvisioningResponseType getQueryProvisioningResponse() {
        return queryProvisioningResponse;
    }

    /**
     * Sets the value of the queryProvisioningResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryProvisioningResponseType }
     *     
     */
    public void setQueryProvisioningResponse(QueryProvisioningResponseType value) {
        this.queryProvisioningResponse = value;
    }

}
