//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 06:23:17 PM GMT 
//


package org.sdmx.resources.sdmxml.schemas.v2_0.registry;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * This document is sent to the registry services to submit provisioning information. A provision agreement is typically sent, wghich has internal references to existing data rpvodiers and dataflows/metadataflows. These elements are also included as possible separate submissions, because it may be necessary to provide datasource and constraint information independent of the establishment of a provision agreement. 
 * 
 * <p>Java class for SubmitProvisioningRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubmitProvisioningRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="ProvisionAgreement" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}ProvisionAgreementType"/>
 *         &lt;element name="DataProviderRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}DataProviderRefType"/>
 *         &lt;element name="DataflowRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}DataflowRefType"/>
 *         &lt;element name="MetadatataflowRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}MetadataflowRefType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubmitProvisioningRequestType", propOrder = {
    "provisionAgreementOrDataProviderRefOrDataflowRef"
})
public class SubmitProvisioningRequestType {

    @XmlElements({
        @XmlElement(name = "DataflowRef", type = DataflowRefType.class),
        @XmlElement(name = "ProvisionAgreement", type = ProvisionAgreementType.class),
        @XmlElement(name = "DataProviderRef", type = DataProviderRefType.class),
        @XmlElement(name = "MetadatataflowRef", type = MetadataflowRefType.class)
    })
    protected List<Object> provisionAgreementOrDataProviderRefOrDataflowRef;

    /**
     * Gets the value of the provisionAgreementOrDataProviderRefOrDataflowRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the provisionAgreementOrDataProviderRefOrDataflowRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProvisionAgreementOrDataProviderRefOrDataflowRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataflowRefType }
     * {@link ProvisionAgreementType }
     * {@link DataProviderRefType }
     * {@link MetadataflowRefType }
     * 
     * 
     */
    public List<Object> getProvisionAgreementOrDataProviderRefOrDataflowRef() {
        if (provisionAgreementOrDataProviderRefOrDataflowRef == null) {
            provisionAgreementOrDataProviderRefOrDataflowRef = new ArrayList<Object>();
        }
        return this.provisionAgreementOrDataProviderRefOrDataflowRef;
    }

}
