//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 06:23:17 PM GMT 
//


package org.sdmx.resources.sdmxml.schemas.v2_0.message;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.sdmx.resources.sdmxml.schemas.v2_0.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MessageGroup_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", "MessageGroup");
    private final static QName _QueryMessage_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", "QueryMessage");
    private final static QName _GenericData_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", "GenericData");
    private final static QName _Header_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", "Header");
    private final static QName _CrossSectionalData_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", "CrossSectionalData");
    private final static QName _UtilityData_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", "UtilityData");
    private final static QName _GenericMetadata_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", "GenericMetadata");
    private final static QName _Structure_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", "Structure");
    private final static QName _RegistryInterface_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", "RegistryInterface");
    private final static QName _CompactData_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", "CompactData");
    private final static QName _MetadataReport_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", "MetadataReport");
    private final static QName _ContactTypeEmail_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", "Email");
    private final static QName _ContactTypeTelephone_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", "Telephone");
    private final static QName _ContactTypeFax_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", "Fax");
    private final static QName _ContactTypeX400_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", "X400");
    private final static QName _ContactTypeURI_QNAME = new QName("http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", "URI");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.sdmx.resources.sdmxml.schemas.v2_0.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QueryMessageType }
     * 
     */
    public QueryMessageType createQueryMessageType() {
        return new QueryMessageType();
    }

    /**
     * Create an instance of {@link RegistryInterfaceType }
     * 
     */
    public RegistryInterfaceType createRegistryInterfaceType() {
        return new RegistryInterfaceType();
    }

    /**
     * Create an instance of {@link CrossSectionalDataType }
     * 
     */
    public CrossSectionalDataType createCrossSectionalDataType() {
        return new CrossSectionalDataType();
    }

    /**
     * Create an instance of {@link GenericMetadataType }
     * 
     */
    public GenericMetadataType createGenericMetadataType() {
        return new GenericMetadataType();
    }

    /**
     * Create an instance of {@link PartyType }
     * 
     */
    public PartyType createPartyType() {
        return new PartyType();
    }

    /**
     * Create an instance of {@link UtilityDataType }
     * 
     */
    public UtilityDataType createUtilityDataType() {
        return new UtilityDataType();
    }

    /**
     * Create an instance of {@link StructureType }
     * 
     */
    public StructureType createStructureType() {
        return new StructureType();
    }

    /**
     * Create an instance of {@link GenericDataType }
     * 
     */
    public GenericDataType createGenericDataType() {
        return new GenericDataType();
    }

    /**
     * Create an instance of {@link ContactType }
     * 
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link CompactDataType }
     * 
     */
    public CompactDataType createCompactDataType() {
        return new CompactDataType();
    }

    /**
     * Create an instance of {@link MetadataReportType }
     * 
     */
    public MetadataReportType createMetadataReportType() {
        return new MetadataReportType();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link MessageGroupType }
     * 
     */
    public MessageGroupType createMessageGroupType() {
        return new MessageGroupType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageGroupType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", name = "MessageGroup")
    public JAXBElement<MessageGroupType> createMessageGroup(MessageGroupType value) {
        return new JAXBElement<MessageGroupType>(_MessageGroup_QNAME, MessageGroupType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", name = "QueryMessage")
    public JAXBElement<QueryMessageType> createQueryMessage(QueryMessageType value) {
        return new JAXBElement<QueryMessageType>(_QueryMessage_QNAME, QueryMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenericDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", name = "GenericData")
    public JAXBElement<GenericDataType> createGenericData(GenericDataType value) {
        return new JAXBElement<GenericDataType>(_GenericData_QNAME, GenericDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HeaderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", name = "Header")
    public JAXBElement<HeaderType> createHeader(HeaderType value) {
        return new JAXBElement<HeaderType>(_Header_QNAME, HeaderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrossSectionalDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", name = "CrossSectionalData")
    public JAXBElement<CrossSectionalDataType> createCrossSectionalData(CrossSectionalDataType value) {
        return new JAXBElement<CrossSectionalDataType>(_CrossSectionalData_QNAME, CrossSectionalDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UtilityDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", name = "UtilityData")
    public JAXBElement<UtilityDataType> createUtilityData(UtilityDataType value) {
        return new JAXBElement<UtilityDataType>(_UtilityData_QNAME, UtilityDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenericMetadataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", name = "GenericMetadata")
    public JAXBElement<GenericMetadataType> createGenericMetadata(GenericMetadataType value) {
        return new JAXBElement<GenericMetadataType>(_GenericMetadata_QNAME, GenericMetadataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", name = "Structure")
    public JAXBElement<StructureType> createStructure(StructureType value) {
        return new JAXBElement<StructureType>(_Structure_QNAME, StructureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistryInterfaceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", name = "RegistryInterface")
    public JAXBElement<RegistryInterfaceType> createRegistryInterface(RegistryInterfaceType value) {
        return new JAXBElement<RegistryInterfaceType>(_RegistryInterface_QNAME, RegistryInterfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompactDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", name = "CompactData")
    public JAXBElement<CompactDataType> createCompactData(CompactDataType value) {
        return new JAXBElement<CompactDataType>(_CompactData_QNAME, CompactDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetadataReportType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", name = "MetadataReport")
    public JAXBElement<MetadataReportType> createMetadataReport(MetadataReportType value) {
        return new JAXBElement<MetadataReportType>(_MetadataReport_QNAME, MetadataReportType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", name = "Email", scope = ContactType.class)
    public JAXBElement<String> createContactTypeEmail(String value) {
        return new JAXBElement<String>(_ContactTypeEmail_QNAME, String.class, ContactType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", name = "Telephone", scope = ContactType.class)
    public JAXBElement<String> createContactTypeTelephone(String value) {
        return new JAXBElement<String>(_ContactTypeTelephone_QNAME, String.class, ContactType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", name = "Fax", scope = ContactType.class)
    public JAXBElement<String> createContactTypeFax(String value) {
        return new JAXBElement<String>(_ContactTypeFax_QNAME, String.class, ContactType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", name = "X400", scope = ContactType.class)
    public JAXBElement<String> createContactTypeX400(String value) {
        return new JAXBElement<String>(_ContactTypeX400_QNAME, String.class, ContactType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", name = "URI", scope = ContactType.class)
    public JAXBElement<String> createContactTypeURI(String value) {
        return new JAXBElement<String>(_ContactTypeURI_QNAME, String.class, ContactType.class, value);
    }

}
