//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 06:23:17 PM GMT 
//


package uk.ac.cardiff.raptor.sdmx.compact;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import org.sdmx.resources.sdmxml.schemas.v2_0.common.AnnotationsType;


/**
 * <p>Java class for DataSetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataSetType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/compact}DataSetType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{urn:uk:ac:cardiff:raptor:sdmx:compact}SiblingGroup"/>
 *         &lt;element ref="{urn:uk:ac:cardiff:raptor:sdmx:compact}Series"/>
 *         &lt;element name="Annotations" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}AnnotationsType"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataSetType", propOrder = {
    "siblingGroupOrSeriesOrAnnotations"
})
public class DataSetType
    extends org.sdmx.resources.sdmxml.schemas.v2_0.compact.DataSetType
{

    @XmlElements({
        @XmlElement(name = "Series", type = SeriesType.class),
        @XmlElement(name = "Annotations", type = AnnotationsType.class),
        @XmlElement(name = "SiblingGroup", type = SiblingGroupType.class)
    })
    protected List<Object> siblingGroupOrSeriesOrAnnotations;

    /**
     * Gets the value of the siblingGroupOrSeriesOrAnnotations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the siblingGroupOrSeriesOrAnnotations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSiblingGroupOrSeriesOrAnnotations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SeriesType }
     * {@link AnnotationsType }
     * {@link SiblingGroupType }
     * 
     * 
     */
    public List<Object> getSiblingGroupOrSeriesOrAnnotations() {
        if (siblingGroupOrSeriesOrAnnotations == null) {
            siblingGroupOrSeriesOrAnnotations = new ArrayList<Object>();
        }
        return this.siblingGroupOrSeriesOrAnnotations;
    }

}
