//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 06:23:17 PM GMT 
//


package uk.ac.cardiff.raptor.sdmx.compact;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CL_TYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CL_TYPE">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EVT"/>
 *     &lt;enumeration value="AUTH"/>
 *     &lt;enumeration value="USG"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CL_TYPE")
@XmlEnum
public enum CLTYPE {


    /**
     * Events
     * 
     */
    EVT,

    /**
     * Authentications
     * 
     */
    AUTH,

    /**
     * Usage Accesses
     * 
     */
    USG;

    public String value() {
        return name();
    }

    public static CLTYPE fromValue(String v) {
        return valueOf(v);
    }

}
