//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 06:23:17 PM GMT 
//


package org.sdmx.resources.sdmxml.schemas.v2_0.registry;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.sdmx.resources.sdmxml.schemas.v2_0.registry package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.sdmx.resources.sdmxml.schemas.v2_0.registry
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SubmitRegistrationResponseType }
     * 
     */
    public SubmitRegistrationResponseType createSubmitRegistrationResponseType() {
        return new SubmitRegistrationResponseType();
    }

    /**
     * Create an instance of {@link ValidityPeriodType }
     * 
     */
    public ValidityPeriodType createValidityPeriodType() {
        return new ValidityPeriodType();
    }

    /**
     * Create an instance of {@link ProvisionAgreementType }
     * 
     */
    public ProvisionAgreementType createProvisionAgreementType() {
        return new ProvisionAgreementType();
    }

    /**
     * Create an instance of {@link SubmitRegistrationRequestType }
     * 
     */
    public SubmitRegistrationRequestType createSubmitRegistrationRequestType() {
        return new SubmitRegistrationRequestType();
    }

    /**
     * Create an instance of {@link QueryProvisioningResponseType }
     * 
     */
    public QueryProvisioningResponseType createQueryProvisioningResponseType() {
        return new QueryProvisioningResponseType();
    }

    /**
     * Create an instance of {@link SubmissionResultType }
     * 
     */
    public SubmissionResultType createSubmissionResultType() {
        return new SubmissionResultType();
    }

    /**
     * Create an instance of {@link ProcessRefType }
     * 
     */
    public ProcessRefType createProcessRefType() {
        return new ProcessRefType();
    }

    /**
     * Create an instance of {@link QueryableDatasourceType }
     * 
     */
    public QueryableDatasourceType createQueryableDatasourceType() {
        return new QueryableDatasourceType();
    }

    /**
     * Create an instance of {@link DataProviderRefType }
     * 
     */
    public DataProviderRefType createDataProviderRefType() {
        return new DataProviderRefType();
    }

    /**
     * Create an instance of {@link KeyFamilyRefType }
     * 
     */
    public KeyFamilyRefType createKeyFamilyRefType() {
        return new KeyFamilyRefType();
    }

    /**
     * Create an instance of {@link StructureType }
     * 
     */
    public StructureType createStructureType() {
        return new StructureType();
    }

    /**
     * Create an instance of {@link DataRegistrationEventsType }
     * 
     */
    public DataRegistrationEventsType createDataRegistrationEventsType() {
        return new DataRegistrationEventsType();
    }

    /**
     * Create an instance of {@link ProvisioningEventType }
     * 
     */
    public ProvisioningEventType createProvisioningEventType() {
        return new ProvisioningEventType();
    }

    /**
     * Create an instance of {@link ProvisioningRepositoryEventsType }
     * 
     */
    public ProvisioningRepositoryEventsType createProvisioningRepositoryEventsType() {
        return new ProvisioningRepositoryEventsType();
    }

    /**
     * Create an instance of {@link ConceptSchemeRefType }
     * 
     */
    public ConceptSchemeRefType createConceptSchemeRefType() {
        return new ConceptSchemeRefType();
    }

    /**
     * Create an instance of {@link ProvisioningStatusType }
     * 
     */
    public ProvisioningStatusType createProvisioningStatusType() {
        return new ProvisioningStatusType();
    }

    /**
     * Create an instance of {@link StructuralRepositoryEventsType }
     * 
     */
    public StructuralRepositoryEventsType createStructuralRepositoryEventsType() {
        return new StructuralRepositoryEventsType();
    }

    /**
     * Create an instance of {@link HierarchicalCodelistRefType }
     * 
     */
    public HierarchicalCodelistRefType createHierarchicalCodelistRefType() {
        return new HierarchicalCodelistRefType();
    }

    /**
     * Create an instance of {@link RegistrationStatusType }
     * 
     */
    public RegistrationStatusType createRegistrationStatusType() {
        return new RegistrationStatusType();
    }

    /**
     * Create an instance of {@link QueryResultType }
     * 
     */
    public QueryResultType createQueryResultType() {
        return new QueryResultType();
    }

    /**
     * Create an instance of {@link CodelistRefType }
     * 
     */
    public CodelistRefType createCodelistRefType() {
        return new CodelistRefType();
    }

    /**
     * Create an instance of {@link NotifyRegistryEventType }
     * 
     */
    public NotifyRegistryEventType createNotifyRegistryEventType() {
        return new NotifyRegistryEventType();
    }

    /**
     * Create an instance of {@link MetadataflowRefType }
     * 
     */
    public MetadataflowRefType createMetadataflowRefType() {
        return new MetadataflowRefType();
    }

    /**
     * Create an instance of {@link StructuralEventType }
     * 
     */
    public StructuralEventType createStructuralEventType() {
        return new StructuralEventType();
    }

    /**
     * Create an instance of {@link DatasourceType }
     * 
     */
    public DatasourceType createDatasourceType() {
        return new DatasourceType();
    }

    /**
     * Create an instance of {@link QueryProvisioningRequestType }
     * 
     */
    public QueryProvisioningRequestType createQueryProvisioningRequestType() {
        return new QueryProvisioningRequestType();
    }

    /**
     * Create an instance of {@link SubmitProvisioningResponseType }
     * 
     */
    public SubmitProvisioningResponseType createSubmitProvisioningResponseType() {
        return new SubmitProvisioningResponseType();
    }

    /**
     * Create an instance of {@link MetadataStructureRefType }
     * 
     */
    public MetadataStructureRefType createMetadataStructureRefType() {
        return new MetadataStructureRefType();
    }

    /**
     * Create an instance of {@link SubmitStructureResponseType }
     * 
     */
    public SubmitStructureResponseType createSubmitStructureResponseType() {
        return new SubmitStructureResponseType();
    }

    /**
     * Create an instance of {@link OrganisationSchemeRefType }
     * 
     */
    public OrganisationSchemeRefType createOrganisationSchemeRefType() {
        return new OrganisationSchemeRefType();
    }

    /**
     * Create an instance of {@link ProvisionAgreementRefType }
     * 
     */
    public ProvisionAgreementRefType createProvisionAgreementRefType() {
        return new ProvisionAgreementRefType();
    }

    /**
     * Create an instance of {@link SubmitStructureRequestType }
     * 
     */
    public SubmitStructureRequestType createSubmitStructureRequestType() {
        return new SubmitStructureRequestType();
    }

    /**
     * Create an instance of {@link SubmitSubscriptionRequestType }
     * 
     */
    public SubmitSubscriptionRequestType createSubmitSubscriptionRequestType() {
        return new SubmitSubscriptionRequestType();
    }

    /**
     * Create an instance of {@link ResultType }
     * 
     */
    public ResultType createResultType() {
        return new ResultType();
    }

    /**
     * Create an instance of {@link ReportingTaxonomyRefType }
     * 
     */
    public ReportingTaxonomyRefType createReportingTaxonomyRefType() {
        return new ReportingTaxonomyRefType();
    }

    /**
     * Create an instance of {@link CategorySchemeRefType }
     * 
     */
    public CategorySchemeRefType createCategorySchemeRefType() {
        return new CategorySchemeRefType();
    }

    /**
     * Create an instance of {@link QueryRegistrationResponseType }
     * 
     */
    public QueryRegistrationResponseType createQueryRegistrationResponseType() {
        return new QueryRegistrationResponseType();
    }

    /**
     * Create an instance of {@link QueryStructureResponseType }
     * 
     */
    public QueryStructureResponseType createQueryStructureResponseType() {
        return new QueryStructureResponseType();
    }

    /**
     * Create an instance of {@link RegistrationEventType }
     * 
     */
    public RegistrationEventType createRegistrationEventType() {
        return new RegistrationEventType();
    }

    /**
     * Create an instance of {@link QueryStructureRequestType }
     * 
     */
    public QueryStructureRequestType createQueryStructureRequestType() {
        return new QueryStructureRequestType();
    }

    /**
     * Create an instance of {@link EventSelectorType }
     * 
     */
    public EventSelectorType createEventSelectorType() {
        return new EventSelectorType();
    }

    /**
     * Create an instance of {@link SubmitProvisioningRequestType }
     * 
     */
    public SubmitProvisioningRequestType createSubmitProvisioningRequestType() {
        return new SubmitProvisioningRequestType();
    }

    /**
     * Create an instance of {@link AgencyRefType }
     * 
     */
    public AgencyRefType createAgencyRefType() {
        return new AgencyRefType();
    }

    /**
     * Create an instance of {@link StructureSetRefType }
     * 
     */
    public StructureSetRefType createStructureSetRefType() {
        return new StructureSetRefType();
    }

    /**
     * Create an instance of {@link QueryRegistrationRequestType }
     * 
     */
    public QueryRegistrationRequestType createQueryRegistrationRequestType() {
        return new QueryRegistrationRequestType();
    }

    /**
     * Create an instance of {@link RegistrationType }
     * 
     */
    public RegistrationType createRegistrationType() {
        return new RegistrationType();
    }

    /**
     * Create an instance of {@link SubmittedStructureType }
     * 
     */
    public SubmittedStructureType createSubmittedStructureType() {
        return new SubmittedStructureType();
    }

    /**
     * Create an instance of {@link SubscriptionType }
     * 
     */
    public SubscriptionType createSubscriptionType() {
        return new SubscriptionType();
    }

    /**
     * Create an instance of {@link MetadataRegistrationEventsType }
     * 
     */
    public MetadataRegistrationEventsType createMetadataRegistrationEventsType() {
        return new MetadataRegistrationEventsType();
    }

    /**
     * Create an instance of {@link DataflowRefType }
     * 
     */
    public DataflowRefType createDataflowRefType() {
        return new DataflowRefType();
    }

    /**
     * Create an instance of {@link SubmitSubscriptionResponseType }
     * 
     */
    public SubmitSubscriptionResponseType createSubmitSubscriptionResponseType() {
        return new SubmitSubscriptionResponseType();
    }

    /**
     * Create an instance of {@link StatusMessageType }
     * 
     */
    public StatusMessageType createStatusMessageType() {
        return new StatusMessageType();
    }

}
