//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 06:23:17 PM GMT 
//


package org.sdmx.resources.sdmxml.schemas.v2_0.registry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * QueryResult contains the results of a specific registry query for a single datasource. If a successful result is a registered dataset, the DataResult element is used. If a successful result is a registered metadataset, the MetadataResult is used. If the query failed, then StatusMessage is included. The timeSeriesMatch attribute is true when the result is an exact match with the key found in the registry - that is, when the registered datasource provides a matching key. It is set to false when the datasource is registered with cube-region constraints, or in any other circumstance when it cannot be established that the sought-for keys have been exactly matched. This is always true when the resulting datasource is the source of a metadata set.
 * 
 * <p>Java class for QueryResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="DataResult" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}ResultType"/>
 *         &lt;element name="MetadataResult" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}ResultType"/>
 *         &lt;element name="StatusMessage" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}StatusMessageType"/>
 *       &lt;/choice>
 *       &lt;attribute name="timeSeriesMatch" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryResultType", propOrder = {
    "dataResult",
    "metadataResult",
    "statusMessage"
})
public class QueryResultType {

    @XmlElement(name = "DataResult")
    protected ResultType dataResult;
    @XmlElement(name = "MetadataResult")
    protected ResultType metadataResult;
    @XmlElement(name = "StatusMessage")
    protected StatusMessageType statusMessage;
    @XmlAttribute(required = true)
    protected boolean timeSeriesMatch;

    /**
     * Gets the value of the dataResult property.
     * 
     * @return
     *     possible object is
     *     {@link ResultType }
     *     
     */
    public ResultType getDataResult() {
        return dataResult;
    }

    /**
     * Sets the value of the dataResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultType }
     *     
     */
    public void setDataResult(ResultType value) {
        this.dataResult = value;
    }

    /**
     * Gets the value of the metadataResult property.
     * 
     * @return
     *     possible object is
     *     {@link ResultType }
     *     
     */
    public ResultType getMetadataResult() {
        return metadataResult;
    }

    /**
     * Sets the value of the metadataResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultType }
     *     
     */
    public void setMetadataResult(ResultType value) {
        this.metadataResult = value;
    }

    /**
     * Gets the value of the statusMessage property.
     * 
     * @return
     *     possible object is
     *     {@link StatusMessageType }
     *     
     */
    public StatusMessageType getStatusMessage() {
        return statusMessage;
    }

    /**
     * Sets the value of the statusMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusMessageType }
     *     
     */
    public void setStatusMessage(StatusMessageType value) {
        this.statusMessage = value;
    }

    /**
     * Gets the value of the timeSeriesMatch property.
     * 
     */
    public boolean isTimeSeriesMatch() {
        return timeSeriesMatch;
    }

    /**
     * Sets the value of the timeSeriesMatch property.
     * 
     */
    public void setTimeSeriesMatch(boolean value) {
        this.timeSeriesMatch = value;
    }

}
