//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 06:23:17 PM GMT 
//


package org.sdmx.resources.sdmxml.schemas.v2_0.registry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.sdmx.resources.sdmxml.schemas.v2_0.common.ActionType;


/**
 * Subscriptions submit a subscription for a registry or repository object.Action indicates what action is being taken by sending the request. RegistryURN is used to identify the subscription in the case of deletion or modification. NotificationMAilTo holds an e-mail address (the "mailto:" protocol); NotificationHTTP holds an http address to which notifications can be addressed as POSTs. SubscriberAssignedID allows the subscriber to specify an ID which will be returned as part of the notification for the subscribed events. Validity period sets a start and end date for the subscription, EventSelector indicates an event or events for the subscription.
 * 
 * <p>Java class for SubscriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubscriptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Action" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}ActionType"/>
 *         &lt;element name="RegistryURN" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="NotificationMailTo" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="NotificationHTTP" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="SubscriberAssignedID" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType" minOccurs="0"/>
 *         &lt;element name="ValidityPeriod" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}ValidityPeriodType"/>
 *         &lt;element name="EventSelector" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/registry}EventSelectorType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubscriptionType", propOrder = {
    "action",
    "registryURN",
    "notificationMailTo",
    "notificationHTTP",
    "subscriberAssignedID",
    "validityPeriod",
    "eventSelector"
})
public class SubscriptionType {

    @XmlElement(name = "Action", required = true)
    protected ActionType action;
    @XmlElement(name = "RegistryURN")
    @XmlSchemaType(name = "anyURI")
    protected String registryURN;
    @XmlElement(name = "NotificationMailTo")
    @XmlSchemaType(name = "anyURI")
    protected String notificationMailTo;
    @XmlElement(name = "NotificationHTTP")
    @XmlSchemaType(name = "anyURI")
    protected String notificationHTTP;
    @XmlElement(name = "SubscriberAssignedID")
    protected String subscriberAssignedID;
    @XmlElement(name = "ValidityPeriod", required = true)
    protected ValidityPeriodType validityPeriod;
    @XmlElement(name = "EventSelector", required = true)
    protected EventSelectorType eventSelector;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the registryURN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistryURN() {
        return registryURN;
    }

    /**
     * Sets the value of the registryURN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistryURN(String value) {
        this.registryURN = value;
    }

    /**
     * Gets the value of the notificationMailTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotificationMailTo() {
        return notificationMailTo;
    }

    /**
     * Sets the value of the notificationMailTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotificationMailTo(String value) {
        this.notificationMailTo = value;
    }

    /**
     * Gets the value of the notificationHTTP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotificationHTTP() {
        return notificationHTTP;
    }

    /**
     * Sets the value of the notificationHTTP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotificationHTTP(String value) {
        this.notificationHTTP = value;
    }

    /**
     * Gets the value of the subscriberAssignedID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriberAssignedID() {
        return subscriberAssignedID;
    }

    /**
     * Sets the value of the subscriberAssignedID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriberAssignedID(String value) {
        this.subscriberAssignedID = value;
    }

    /**
     * Gets the value of the validityPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link ValidityPeriodType }
     *     
     */
    public ValidityPeriodType getValidityPeriod() {
        return validityPeriod;
    }

    /**
     * Sets the value of the validityPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidityPeriodType }
     *     
     */
    public void setValidityPeriod(ValidityPeriodType value) {
        this.validityPeriod = value;
    }

    /**
     * Gets the value of the eventSelector property.
     * 
     * @return
     *     possible object is
     *     {@link EventSelectorType }
     *     
     */
    public EventSelectorType getEventSelector() {
        return eventSelector;
    }

    /**
     * Sets the value of the eventSelector property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventSelectorType }
     *     
     */
    public void setEventSelector(EventSelectorType value) {
        this.eventSelector = value;
    }

}
