//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 06:23:17 PM GMT 
//


package org.sdmx.resources.sdmxml.schemas.v2_0.generic;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.sdmx.resources.sdmxml.schemas.v2_0.common.ActionType;
import org.sdmx.resources.sdmxml.schemas.v2_0.common.AnnotationsType;


/**
 * DataSetType defines the structure of a data set. This consists of a key family reference which contains the ID of the key family, and the attribute values attached at the data set level. A DataSet may be used to transmit documentation (that is, only attribute values), data, or a combination of both. If providing only documentation, you need not send the complete set of attributes. If transmitting only data, the Group may be omitted if desired. Uniqueness constraints are defined for the attributes of the data set. If dataset-level attributes are sent in a delete message, then any valid attribute value will indicate that the current attribute value should be deleted. The keyFamilyURI attribute is provided to allow a URI (typically a URL) to be provided, pointing to an SDMX-ML Structure message describing the key family. Attributes are provided for describing the contents of a data or metadata set, which are particularly important for interactions with the SDMX Registry: datasetID, dataProviderSchemeAgencyID, dataProviderSchemeID, dataflowAgencyID, and dataflowID all take the IDs specified by the attribute names. The action attribute indicates whether the file is appending, replacing, or deleting. Attributes reportingBeginDate, reportingEndDate, validFromDate, and validToDate are inclusive. publicationYear holds the ISO 8601 four-digit year, and publicationPeriod specifies the period of publication of the data in terms of whatever provisioning agreements might be in force (ie, "Q1 2005" if that is the time of publication for a data set published on a quarterly basis).
 * 	
 * 
 * <p>Java class for DataSetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataSetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="KeyFamilyRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType"/>
 *         &lt;element name="Attributes" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/generic}ValuesType" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="Group" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/generic}GroupType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="Series" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/generic}SeriesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="Annotations" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}AnnotationsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="keyFamilyURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="datasetID" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType" />
 *       &lt;attribute name="dataProviderSchemeAgencyId" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType" />
 *       &lt;attribute name="dataProviderSchemeId" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType" />
 *       &lt;attribute name="dataProviderID" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType" />
 *       &lt;attribute name="dataflowAgencyID" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType" />
 *       &lt;attribute name="dataflowID" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType" />
 *       &lt;attribute name="action" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}ActionType" />
 *       &lt;attribute name="reportingBeginDate" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}TimePeriodType" />
 *       &lt;attribute name="reportingEndDate" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}TimePeriodType" />
 *       &lt;attribute name="validFromDate" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}TimePeriodType" />
 *       &lt;attribute name="validToDate" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}TimePeriodType" />
 *       &lt;attribute name="publicationYear" type="{http://www.w3.org/2001/XMLSchema}gYear" />
 *       &lt;attribute name="publicationPeriod" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}TimePeriodType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataSetType", propOrder = {
    "keyFamilyRef",
    "attributes",
    "groupOrSeries",
    "annotations"
})
public class DataSetType {

    @XmlElement(name = "KeyFamilyRef", required = true)
    protected String keyFamilyRef;
    @XmlElement(name = "Attributes")
    protected ValuesType attributes;
    @XmlElements({
        @XmlElement(name = "Group", type = GroupType.class),
        @XmlElement(name = "Series", type = SeriesType.class)
    })
    protected List<Object> groupOrSeries;
    @XmlElement(name = "Annotations")
    protected AnnotationsType annotations;
    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String keyFamilyURI;
    @XmlAttribute
    protected String datasetID;
    @XmlAttribute
    protected String dataProviderSchemeAgencyId;
    @XmlAttribute
    protected String dataProviderSchemeId;
    @XmlAttribute
    protected String dataProviderID;
    @XmlAttribute
    protected String dataflowAgencyID;
    @XmlAttribute
    protected String dataflowID;
    @XmlAttribute
    protected ActionType action;
    @XmlAttribute
    protected String reportingBeginDate;
    @XmlAttribute
    protected String reportingEndDate;
    @XmlAttribute
    protected String validFromDate;
    @XmlAttribute
    protected String validToDate;
    @XmlAttribute
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar publicationYear;
    @XmlAttribute
    protected String publicationPeriod;

    /**
     * Gets the value of the keyFamilyRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyFamilyRef() {
        return keyFamilyRef;
    }

    /**
     * Sets the value of the keyFamilyRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyFamilyRef(String value) {
        this.keyFamilyRef = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link ValuesType }
     *     
     */
    public ValuesType getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValuesType }
     *     
     */
    public void setAttributes(ValuesType value) {
        this.attributes = value;
    }

    /**
     * Gets the value of the groupOrSeries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupOrSeries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroupOrSeries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GroupType }
     * {@link SeriesType }
     * 
     * 
     */
    public List<Object> getGroupOrSeries() {
        if (groupOrSeries == null) {
            groupOrSeries = new ArrayList<Object>();
        }
        return this.groupOrSeries;
    }

    /**
     * Gets the value of the annotations property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationsType }
     *     
     */
    public AnnotationsType getAnnotations() {
        return annotations;
    }

    /**
     * Sets the value of the annotations property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationsType }
     *     
     */
    public void setAnnotations(AnnotationsType value) {
        this.annotations = value;
    }

    /**
     * Gets the value of the keyFamilyURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyFamilyURI() {
        return keyFamilyURI;
    }

    /**
     * Sets the value of the keyFamilyURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyFamilyURI(String value) {
        this.keyFamilyURI = value;
    }

    /**
     * Gets the value of the datasetID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatasetID() {
        return datasetID;
    }

    /**
     * Sets the value of the datasetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatasetID(String value) {
        this.datasetID = value;
    }

    /**
     * Gets the value of the dataProviderSchemeAgencyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataProviderSchemeAgencyId() {
        return dataProviderSchemeAgencyId;
    }

    /**
     * Sets the value of the dataProviderSchemeAgencyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataProviderSchemeAgencyId(String value) {
        this.dataProviderSchemeAgencyId = value;
    }

    /**
     * Gets the value of the dataProviderSchemeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataProviderSchemeId() {
        return dataProviderSchemeId;
    }

    /**
     * Sets the value of the dataProviderSchemeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataProviderSchemeId(String value) {
        this.dataProviderSchemeId = value;
    }

    /**
     * Gets the value of the dataProviderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataProviderID() {
        return dataProviderID;
    }

    /**
     * Sets the value of the dataProviderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataProviderID(String value) {
        this.dataProviderID = value;
    }

    /**
     * Gets the value of the dataflowAgencyID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataflowAgencyID() {
        return dataflowAgencyID;
    }

    /**
     * Sets the value of the dataflowAgencyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataflowAgencyID(String value) {
        this.dataflowAgencyID = value;
    }

    /**
     * Gets the value of the dataflowID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataflowID() {
        return dataflowID;
    }

    /**
     * Sets the value of the dataflowID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataflowID(String value) {
        this.dataflowID = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the reportingBeginDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingBeginDate() {
        return reportingBeginDate;
    }

    /**
     * Sets the value of the reportingBeginDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingBeginDate(String value) {
        this.reportingBeginDate = value;
    }

    /**
     * Gets the value of the reportingEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingEndDate() {
        return reportingEndDate;
    }

    /**
     * Sets the value of the reportingEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingEndDate(String value) {
        this.reportingEndDate = value;
    }

    /**
     * Gets the value of the validFromDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidFromDate() {
        return validFromDate;
    }

    /**
     * Sets the value of the validFromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidFromDate(String value) {
        this.validFromDate = value;
    }

    /**
     * Gets the value of the validToDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidToDate() {
        return validToDate;
    }

    /**
     * Sets the value of the validToDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidToDate(String value) {
        this.validToDate = value;
    }

    /**
     * Gets the value of the publicationYear property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPublicationYear() {
        return publicationYear;
    }

    /**
     * Sets the value of the publicationYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPublicationYear(XMLGregorianCalendar value) {
        this.publicationYear = value;
    }

    /**
     * Gets the value of the publicationPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicationPeriod() {
        return publicationPeriod;
    }

    /**
     * Sets the value of the publicationPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicationPeriod(String value) {
        this.publicationPeriod = value;
    }

}
