//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.08 at 06:23:17 PM GMT 
//


package org.sdmx.resources.sdmxml.schemas.v2_0.metadatareport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.sdmx.resources.sdmxml.schemas.v2_0.common.ActionType;


/**
 * MetadataReportType defines the structure of a metadata structure definition-specific Metadata Report. This consists of a MetadataStructureRef which holds the ID fo the metadata structure, and MetadataStructureAgencyRef, which holds the ID of the maintraenance agency of the metadata structure, and Version, which provides the version number of the referenced metadata structure definition. If not provided, version is assumed to be "1.0". This type is designed to be extended to hold the metadata-structure-sepcific fields needed to validate a specific metadata report.
 * 	
 * 
 * <p>Java class for MetadataSetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MetadataSetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MetadataStructureRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType"/>
 *         &lt;element name="MetadataStructureAgencyRef" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType"/>
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="MetadataStructureURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="datasetID" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType" />
 *       &lt;attribute name="dataProviderSchemeAgencyId" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType" />
 *       &lt;attribute name="dataProviderSchemeId" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType" />
 *       &lt;attribute name="dataProviderID" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType" />
 *       &lt;attribute name="dataflowAgencyID" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType" />
 *       &lt;attribute name="dataflowID" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}IDType" />
 *       &lt;attribute name="action" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}ActionType" />
 *       &lt;attribute name="reportingBeginDate" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}TimePeriodType" />
 *       &lt;attribute name="reportingEndDate" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}TimePeriodType" />
 *       &lt;attribute name="validFromDate" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}TimePeriodType" />
 *       &lt;attribute name="validToDate" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}TimePeriodType" />
 *       &lt;attribute name="publicationYear" type="{http://www.w3.org/2001/XMLSchema}gYear" />
 *       &lt;attribute name="publicationPeriod" type="{http://www.SDMX.org/resources/SDMXML/schemas/v2_0/common}TimePeriodType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MetadataSetType", propOrder = {
    "metadataStructureRef",
    "metadataStructureAgencyRef",
    "version"
})
public class MetadataSetType {

    @XmlElement(name = "MetadataStructureRef", required = true)
    protected String metadataStructureRef;
    @XmlElement(name = "MetadataStructureAgencyRef", required = true)
    protected String metadataStructureAgencyRef;
    @XmlElement(name = "Version")
    protected String version;
    @XmlAttribute(name = "MetadataStructureURI")
    @XmlSchemaType(name = "anyURI")
    protected String metadataStructureURI;
    @XmlAttribute
    protected String datasetID;
    @XmlAttribute
    protected String dataProviderSchemeAgencyId;
    @XmlAttribute
    protected String dataProviderSchemeId;
    @XmlAttribute
    protected String dataProviderID;
    @XmlAttribute
    protected String dataflowAgencyID;
    @XmlAttribute
    protected String dataflowID;
    @XmlAttribute
    protected ActionType action;
    @XmlAttribute
    protected String reportingBeginDate;
    @XmlAttribute
    protected String reportingEndDate;
    @XmlAttribute
    protected String validFromDate;
    @XmlAttribute
    protected String validToDate;
    @XmlAttribute
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar publicationYear;
    @XmlAttribute
    protected String publicationPeriod;

    /**
     * Gets the value of the metadataStructureRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetadataStructureRef() {
        return metadataStructureRef;
    }

    /**
     * Sets the value of the metadataStructureRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetadataStructureRef(String value) {
        this.metadataStructureRef = value;
    }

    /**
     * Gets the value of the metadataStructureAgencyRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetadataStructureAgencyRef() {
        return metadataStructureAgencyRef;
    }

    /**
     * Sets the value of the metadataStructureAgencyRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetadataStructureAgencyRef(String value) {
        this.metadataStructureAgencyRef = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the metadataStructureURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetadataStructureURI() {
        return metadataStructureURI;
    }

    /**
     * Sets the value of the metadataStructureURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetadataStructureURI(String value) {
        this.metadataStructureURI = value;
    }

    /**
     * Gets the value of the datasetID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatasetID() {
        return datasetID;
    }

    /**
     * Sets the value of the datasetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatasetID(String value) {
        this.datasetID = value;
    }

    /**
     * Gets the value of the dataProviderSchemeAgencyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataProviderSchemeAgencyId() {
        return dataProviderSchemeAgencyId;
    }

    /**
     * Sets the value of the dataProviderSchemeAgencyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataProviderSchemeAgencyId(String value) {
        this.dataProviderSchemeAgencyId = value;
    }

    /**
     * Gets the value of the dataProviderSchemeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataProviderSchemeId() {
        return dataProviderSchemeId;
    }

    /**
     * Sets the value of the dataProviderSchemeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataProviderSchemeId(String value) {
        this.dataProviderSchemeId = value;
    }

    /**
     * Gets the value of the dataProviderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataProviderID() {
        return dataProviderID;
    }

    /**
     * Sets the value of the dataProviderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataProviderID(String value) {
        this.dataProviderID = value;
    }

    /**
     * Gets the value of the dataflowAgencyID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataflowAgencyID() {
        return dataflowAgencyID;
    }

    /**
     * Sets the value of the dataflowAgencyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataflowAgencyID(String value) {
        this.dataflowAgencyID = value;
    }

    /**
     * Gets the value of the dataflowID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataflowID() {
        return dataflowID;
    }

    /**
     * Sets the value of the dataflowID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataflowID(String value) {
        this.dataflowID = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the reportingBeginDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingBeginDate() {
        return reportingBeginDate;
    }

    /**
     * Sets the value of the reportingBeginDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingBeginDate(String value) {
        this.reportingBeginDate = value;
    }

    /**
     * Gets the value of the reportingEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingEndDate() {
        return reportingEndDate;
    }

    /**
     * Sets the value of the reportingEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingEndDate(String value) {
        this.reportingEndDate = value;
    }

    /**
     * Gets the value of the validFromDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidFromDate() {
        return validFromDate;
    }

    /**
     * Sets the value of the validFromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidFromDate(String value) {
        this.validFromDate = value;
    }

    /**
     * Gets the value of the validToDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidToDate() {
        return validToDate;
    }

    /**
     * Sets the value of the validToDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidToDate(String value) {
        this.validToDate = value;
    }

    /**
     * Gets the value of the publicationYear property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPublicationYear() {
        return publicationYear;
    }

    /**
     * Sets the value of the publicationYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPublicationYear(XMLGregorianCalendar value) {
        this.publicationYear = value;
    }

    /**
     * Gets the value of the publicationPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicationPeriod() {
        return publicationPeriod;
    }

    /**
     * Sets the value of the publicationPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicationPeriod(String value) {
        this.publicationPeriod = value;
    }

}
